engines:
  tslint:
    enabled: true
    channel: beta
    config: tslint.json
  duplication:
    enabled: true
    config:
      languages:
      - typescript
  fixme:
      enabled: true
plugins:
  tslint:
    enabled: true
    config: tslint.json
ratings:
  paths:
  - src/**
exclude_paths:
- doc/**/*
- dist/**/*
- test/**/*
- vendor/**/*
- template/**/*
